spring:
  profiles:
    active: local-h2
  threads:
    virtual:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ams;MODE=MYSQL;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
  exposed:
    show-sql: true
    generate-ddl: true
