spring:
  profiles:
    active: local-h2

---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:ams;MODE=MYSQL;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:

---

spring:
  config:
    activate:
      on-profile: konai
  data:
    mongodb:
      host: 118.33.122.32
      port: 27017
      database: ams
      username: ams
      password: ams1234
