spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ams
      username: ams
      password: ams1234

---

spring:
  config:
    activate:
      on-profile: office
  data:
    mongodb:
      host: 118.33.122.32
      port: 27017
      database: ams
      username: ams
      password: ams1234
