= Demo AMS API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
== 개요

AMS(Academy Management System) API 문서입니다.

[[student-api]]
== 학생 관리 API

학생 정보를 관리하기 위한 API 입니다.

[[student-create]]

=== 학생 정보 생성

==== 학생 정보 생성 성공 요청/응답
operation::student/create[snippets='http-request,request-fields,http-response,response-fields']
==== 학생 정보 중복 생성 에러 요청/응답
operation::student/create-duplicate-error[snippets='http-response,response-fields']
==== 학생 정보 필수 입력 누락 에러 요청/응답
operation::student/create-missing-name-error[snippets='http-response,response-fields']

[[student-find-one]]

=== 학생 정보 단건 조회

==== 학생 정보 단건 조회 성공 요청/응답
operation::student/find-one[snippets='http-response,response-fields']
==== 학생 정보 단건 조회 Not Found 에러 요청/응답
operation::student/find-one-not-found-error[snippets='http-response,response-fields']

[[student-scroll]]

=== 학생 정보 스크롤 조회

==== 학생 정보 스크롤 조회 성공 요청/응답
operation::student/scroll[snippets='http-response,response-fields']

[[student-update]]

=== 학생 정보 수정

==== 학생 정보 수정 성공 요청/응답
operation::student/update[snippets='http-response,response-fields']
==== 학생 정보 수정 Not Found 에러 요청/응답
operation::student/update-not-found-error[snippets='http-response,response-fields']
